display_homepage:
    path:    /show/geocache/{code}
    defaults: { _controller: DisplayBundle:Default:geocache }

display_user:
    path:    /show/user/{uuid}
    defaults: { _controller: DisplayBundle:Default:user }

search_nearest_geocaches:
    path:    /find/geocaches/radius/{latitude}/{longitude}/{radius}
    defaults: { _controller: DisplayBundle:Search:findNearestGeocache }